return {
  ["workshop-1185229307"]={
    configuration_options={
      CAMERA=true,
      CAPTURE=false,
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      GLOBAL=false,
      GLOBAL_NUMBERS=false,
      HEADER_CLIENT=false,
      HEADER_SERVER=false,
      HORIZONTAL_OFFSET=0,
      TAG="EPIC",
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-2477889104"]={
    configuration_options={
      BADGE_BG_BRIGHTNESS=60,
      BADGE_BG_OPACITY=100,
      COLOR_DOMESTICATION_DEFAULT="BEIGE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      ClientConfig=false,
      EnableSounds=false,
      GapModifier=0,
      HEALTH_BADGE_CLEAR_BG=false,
      HungerThreshold=15,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_BADGE_SETTINGS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="TheForge",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-2659976744"]={ configuration_options={  }, enabled=true },
  ["workshop-2823530744"]={
    configuration_options={
      amulet_slot=true,
      backpack_slot=true,
      chesspiece_fix=true,
      compass_slot=false,
      drop_hand_item_when_heavy=true,
      show_compass=true,
      slots_bg_length_adapter=0,
      slots_bg_length_adapter_no_bg=false,
      slots_num=0 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=false,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  } 
}