return {
  ["workshop-2659976744"]={ configuration_options={  }, enabled=true },
  ["workshop-2823530744"]={
    configuration_options={
      amulet_slot=true,
      backpack_slot=true,
      chesspiece_fix=true,
      compass_slot=false,
      drop_hand_item_when_heavy=true,
      show_compass=true,
      slots_bg_length_adapter=0,
      slots_bg_length_adapter_no_bg=false,
      slots_num=0 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=false,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  } 
}