return {
  ["workshop-1750657150"]={
    configuration_options={
      amount_of_numbers="low",
      display_mode="straight",
      dmg_only="on",
      number_duration="short",
      number_size="atomic",
      show_beaverness="off",
      show_decimal_points="no",
      show_fueled="off",
      show_hunger="off",
      show_moisture="off",
      show_sanity="off",
      show_work="off",
      size_scale="default" 
    },
    enabled=true 
  },
  ["workshop-2659976744"]={ configuration_options={  }, enabled=true },
  ["workshop-2823530744"]={
    configuration_options={
      amulet_slot=true,
      backpack_slot=true,
      chesspiece_fix=true,
      compass_slot=false,
      drop_hand_item_when_heavy=true,
      show_compass=true,
      slots_bg_length_adapter=0,
      slots_bg_length_adapter_no_bg=false,
      slots_num=0 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=false,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  } 
}